//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsDamageMeter.Languages {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Gui : global::System.Configuration.ApplicationSettingsBase {
        
        private static Gui defaultInstance = ((Gui)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Gui())));
        
        public static Gui Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Minimize")]
        public string MinimizeToolTip {
            get {
                return ((string)(this["MinimizeToolTip"]));
            }
            set {
                this["MinimizeToolTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Options")]
        public string OptionsToolTip {
            get {
                return ((string)(this["OptionsToolTip"]));
            }
            set {
                this["OptionsToolTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Close")]
        public string CloseToolTip {
            get {
                return ((string)(this["CloseToolTip"]));
            }
            set {
                this["CloseToolTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Opacity")]
        public string OpacityToolTip {
            get {
                return ((string)(this["OpacityToolTip"]));
            }
            set {
                this["OpacityToolTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Top Most")]
        public string TopMostToolTip {
            get {
                return ((string)(this["TopMostToolTip"]));
            }
            set {
                this["TopMostToolTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resize")]
        public string ResizeToolTip {
            get {
                return ((string)(this["ResizeToolTip"]));
            }
            set {
                this["ResizeToolTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Locate Log...")]
        public string OptionsMenuLocateLog {
            get {
                return ((string)(this["OptionsMenuLocateLog"]));
            }
            set {
                this["OptionsMenuLocateLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ignore List...")]
        public string OptionsMenuIgnoreList {
            get {
                return ((string)(this["OptionsMenuIgnoreList"]));
            }
            set {
                this["OptionsMenuIgnoreList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Help")]
        public string OptionsMenuHelp {
            get {
                return ((string)(this["OptionsMenuHelp"]));
            }
            set {
                this["OptionsMenuHelp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("About")]
        public string OptionsMenuAbout {
            get {
                return ((string)(this["OptionsMenuAbout"]));
            }
            set {
                this["OptionsMenuAbout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Copy You")]
        public string PlayerMenuCopyYou {
            get {
                return ((string)(this["PlayerMenuCopyYou"]));
            }
            set {
                this["PlayerMenuCopyYou"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Copy All")]
        public string PlayerMenuCopyAll {
            get {
                return ((string)(this["PlayerMenuCopyAll"]));
            }
            set {
                this["PlayerMenuCopyAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hide Others")]
        public string PlayerMenuHideOthers {
            get {
                return ((string)(this["PlayerMenuHideOthers"]));
            }
            set {
                this["PlayerMenuHideOthers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Remove")]
        public string PlayerMenuRemove {
            get {
                return ((string)(this["PlayerMenuRemove"]));
            }
            set {
                this["PlayerMenuRemove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ignore")]
        public string PlayerMenuIgnore {
            get {
                return ((string)(this["PlayerMenuIgnore"]));
            }
            set {
                this["PlayerMenuIgnore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Group Member")]
        public string PlayerMenuGroupMember {
            get {
                return ((string)(this["PlayerMenuGroupMember"]));
            }
            set {
                this["PlayerMenuGroupMember"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OK")]
        public string OKButton {
            get {
                return ((string)(this["OKButton"]));
            }
            set {
                this["OKButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cancel")]
        public string CancelButton {
            get {
                return ((string)(this["CancelButton"]));
            }
            set {
                this["CancelButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Add Group Member")]
        public string AddGroupMemberTitle {
            get {
                return ((string)(this["AddGroupMemberTitle"]));
            }
            set {
                this["AddGroupMemberTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This is an invalid name. Valid names begin with a Capital letter and contain no s" +
            "paces or symbols.")]
        public string InvalidNameMessage {
            get {
                return ((string)(this["InvalidNameMessage"]));
            }
            set {
                this["InvalidNameMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Add Member by Name")]
        public string PlayerMenuAddMemberByName {
            get {
                return ((string)(this["PlayerMenuAddMemberByName"]));
            }
            set {
                this["PlayerMenuAddMemberByName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Running")]
        public string RunningToolTip {
            get {
                return ((string)(this["RunningToolTip"]));
            }
            set {
                this["RunningToolTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Disabled")]
        public string DisabledToolTip {
            get {
                return ((string)(this["DisabledToolTip"]));
            }
            set {
                this["DisabledToolTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("total")]
        public string PlayerToolTipTotal {
            get {
                return ((string)(this["PlayerToolTipTotal"]));
            }
            set {
                this["PlayerToolTipTotal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dps")]
        public string PlayerToolTipDps {
            get {
                return ((string)(this["PlayerToolTipDps"]));
            }
            set {
                this["PlayerToolTipDps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("peak")]
        public string PlayerToolTipPeak {
            get {
                return ((string)(this["PlayerToolTipPeak"]));
            }
            set {
                this["PlayerToolTipPeak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("biggest hit")]
        public string PlayerToolTipBiggestHit {
            get {
                return ((string)(this["PlayerToolTipBiggestHit"]));
            }
            set {
                this["PlayerToolTipBiggestHit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unable to locate chat log. Please refer to the documentation for instructions on " +
            "setting up Aion to create the log or click \"Options -> Locate Log...\"")]
        public string OpenLogError {
            get {
                return ((string)(this["OpenLogError"]));
            }
            set {
                this["OpenLogError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xp hour")]
        public string PlayerToolTipExp {
            get {
                return ((string)(this["PlayerToolTipExp"]));
            }
            set {
                this["PlayerToolTipExp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kinah hour")]
        public string PlayerToolTipKinah {
            get {
                return ((string)(this["PlayerToolTipKinah"]));
            }
            set {
                this["PlayerToolTipKinah"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White Damage")]
        public string WhiteDamage {
            get {
                return ((string)(this["WhiteDamage"]));
            }
            set {
                this["WhiteDamage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Breakdown")]
        public string Breakdown {
            get {
                return ((string)(this["Breakdown"]));
            }
            set {
                this["Breakdown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Main View")]
        public string OptionsMenuView {
            get {
                return ((string)(this["OptionsMenuView"]));
            }
            set {
                this["OptionsMenuView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Damage")]
        public string OptionsMenuDamage {
            get {
                return ((string)(this["OptionsMenuDamage"]));
            }
            set {
                this["OptionsMenuDamage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dps")]
        public string OptionsMenuDps {
            get {
                return ((string)(this["OptionsMenuDps"]));
            }
            set {
                this["OptionsMenuDps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Percent")]
        public string OptionsMenuPercent {
            get {
                return ((string)(this["OptionsMenuPercent"]));
            }
            set {
                this["OptionsMenuPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Experience")]
        public string OptionsMenuExperience {
            get {
                return ((string)(this["OptionsMenuExperience"]));
            }
            set {
                this["OptionsMenuExperience"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kinah")]
        public string OptionsMenuKinah {
            get {
                return ((string)(this["OptionsMenuKinah"]));
            }
            set {
                this["OptionsMenuKinah"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sorting")]
        public string OptionsMenuSorting {
            get {
                return ((string)(this["OptionsMenuSorting"]));
            }
            set {
                this["OptionsMenuSorting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Name")]
        public string OptionsMenuName {
            get {
                return ((string)(this["OptionsMenuName"]));
            }
            set {
                this["OptionsMenuName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reset Damage")]
        public string OptionsMenuResetDamage {
            get {
                return ((string)(this["OptionsMenuResetDamage"]));
            }
            set {
                this["OptionsMenuResetDamage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Clear All")]
        public string OptionsMenuClearAll {
            get {
                return ((string)(this["OptionsMenuClearAll"]));
            }
            set {
                this["OptionsMenuClearAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("View Skills")]
        public string PlayerMenuViewSkills {
            get {
                return ((string)(this["PlayerMenuViewSkills"]));
            }
            set {
                this["PlayerMenuViewSkills"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%n %d")]
        public string ShortCopyFormat {
            get {
                return ((string)(this["ShortCopyFormat"]));
            }
            set {
                this["ShortCopyFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%n %d (%s dps)(%p%)")]
        public string LongCopyFormat {
            get {
                return ((string)(this["LongCopyFormat"]));
            }
            set {
                this["LongCopyFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Group Only")]
        public string PlayerMenuGroupOnly {
            get {
                return ((string)(this["PlayerMenuGroupOnly"]));
            }
            set {
                this["PlayerMenuGroupOnly"] = value;
            }
        }
    }
}
