//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsDamageMeter.Languages {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Regex : global::System.Configuration.ApplicationSettingsBase {
        
        private static Regex defaultInstance = ((Regex)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Regex())));
        
        public static Regex Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?<time>[^a-zA-Z]+) : (?<name>.+) inflicted (?<damage>[^a-zA-Z]+) damage on (?<ta" +
            "rget>.+)\\.")]
        public string DamageInflicted {
            get {
                return ((string)(this["DamageInflicted"]));
            }
            set {
                this["DamageInflicted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?<time>[^a-zA-Z]+) : (?<name>.+) inflicted (?<damage>[^a-zA-Z]+) damage on (?<ta" +
            "rget>.+).+by using (?<skill>.+)\\.")]
        public string DamageInflictedSkill {
            get {
                return ((string)(this["DamageInflictedSkill"]));
            }
            set {
                this["DamageInflictedSkill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?<time>[^a-zA-Z]+) : Critical Hit! (?<name>.+) inflicted (?<damage>[^a-zA-Z]+) c" +
            "ritical damage on (?<target>.+)\\.")]
        public string CriticalInflicted {
            get {
                return ((string)(this["CriticalInflicted"]));
            }
            set {
                this["CriticalInflicted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?<time>[^a-zA-Z]+) : (?<name>.+) inflicted continuous damage on (?<target>.+).+b" +
            "y using (?<skill>.+)\\.")]
        public string ContinuousInflicted {
            get {
                return ((string)(this["ContinuousInflicted"]));
            }
            set {
                this["ContinuousInflicted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?<time>[^a-zA-Z]+) : (?<name>.+) used (?<skill>.+) to inflict the continuous dam" +
            "age effect on (?<target>.+)\\.")]
        public string OtherContinuousInflicted {
            get {
                return ((string)(this["OtherContinuousInflicted"]));
            }
            set {
                this["OtherContinuousInflicted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?<time>[^a-zA-Z]+) : (?<target>.+) received (?<damage>[^a-zA-Z]+) damage due to " +
            "the effect of (?<skill>.+)\\.")]
        public string SkillDamageInflicted {
            get {
                return ((string)(this["SkillDamageInflicted"]));
            }
            set {
                this["SkillDamageInflicted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?<time>[^a-zA-Z]+) : (?<name>.+) has joined your group\\.")]
        public string JoinedGroup {
            get {
                return ((string)(this["JoinedGroup"]));
            }
            set {
                this["JoinedGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?<time>[^a-zA-Z]+) : (?<name>.+) has left your group\\.")]
        public string LeftGroup {
            get {
                return ((string)(this["LeftGroup"]));
            }
            set {
                this["LeftGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?<time>[^a-zA-Z]+) : (?<name>.+) summoned (?<pet>.+) by using (?<skill>.+) to le" +
            "t it attack (?<target>.+)\\.")]
        public string PetSummoned {
            get {
                return ((string)(this["PetSummoned"]));
            }
            set {
                this["PetSummoned"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?<time>[^a-zA-Z]+) : (?<name>.+) has summoned (?<pet>.+) to attack (?<target>.+)" +
            " by using (?<skill>.+)\\.")]
        public string OtherPetSummoned {
            get {
                return ((string)(this["OtherPetSummoned"]));
            }
            set {
                this["OtherPetSummoned"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?<time>[^a-zA-Z]+) : (?<name>[a-zA-Z]+) received (?<damage>[^a-zA-Z]+) damage")]
        public string DamageReceived {
            get {
                return ((string)(this["DamageReceived"]));
            }
            set {
                this["DamageReceived"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\[charname:")]
        public string Chat {
            get {
                return ((string)(this["Chat"]));
            }
            set {
                this["Chat"] = value;
            }
        }
    }
}
