//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsDamageMeter.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClassList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClassList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KingsDamageMeter.Localization.ClassList", typeof(ClassList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assassin.
        /// </summary>
        internal static string Assassin {
            get {
                return ResourceManager.GetString("Assassin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chanter.
        /// </summary>
        internal static string Chanter {
            get {
                return ResourceManager.GetString("Chanter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleric.
        /// </summary>
        internal static string Cleric {
            get {
                return ResourceManager.GetString("Cleric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gladiator.
        /// </summary>
        internal static string Gladiator {
            get {
                return ResourceManager.GetString("Gladiator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranger.
        /// </summary>
        internal static string Ranger {
            get {
                return ResourceManager.GetString("Ranger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorcerer.
        /// </summary>
        internal static string Sorcerer {
            get {
                return ResourceManager.GetString("Sorcerer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiritmaster.
        /// </summary>
        internal static string Spiritmaster {
            get {
                return ResourceManager.GetString("Spiritmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templar.
        /// </summary>
        internal static string Templar {
            get {
                return ResourceManager.GetString("Templar", resourceCulture);
            }
        }
    }
}
