//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsDamageMeter.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WindowMainRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WindowMainRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KingsDamageMeter.Localization.WindowMainRes", typeof(WindowMainRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutMenuHeader {
            get {
                return ResourceManager.GetString("AboutMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Group Member....
        /// </summary>
        internal static string AddByNameMenuHeader {
            get {
                return ResourceManager.GetString("AddByNameMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abyss Points.
        /// </summary>
        internal static string ApMainViewMenuHeader {
            get {
                return ResourceManager.GetString("ApMainViewMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseBtnToolTip {
            get {
                return ResourceManager.GetString("CloseBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close?.
        /// </summary>
        internal static string ConfirmCloseCaption {
            get {
                return ResourceManager.GetString("ConfirmCloseCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to close King&apos;s Damage Meter?.
        /// </summary>
        internal static string ConfirmCloseMessage {
            get {
                return ResourceManager.GetString("ConfirmCloseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string DamageMainViewMenuHeader {
            get {
                return ResourceManager.GetString("DamageMainViewMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dps.
        /// </summary>
        internal static string DpsMainViewMenuHeader {
            get {
                return ResourceManager.GetString("DpsMainViewMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        internal static string ExperienceMainViewMenuHeader {
            get {
                return ResourceManager.GetString("ExperienceMainViewMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp per Hour:.
        /// </summary>
        internal static string ExpPerHourToolTip {
            get {
                return ResourceManager.GetString("ExpPerHourToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Only.
        /// </summary>
        internal static string GroupOnlyMenuHeader {
            get {
                return ResourceManager.GetString("GroupOnlyMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpMenuHeader {
            get {
                return ResourceManager.GetString("HelpMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Only.
        /// </summary>
        internal static string HideOthersMenuHeader {
            get {
                return ResourceManager.GetString("HideOthersMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore List....
        /// </summary>
        internal static string IgnoreListMenuHeader {
            get {
                return ResourceManager.GetString("IgnoreListMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earned:.
        /// </summary>
        internal static string KinahEarnedToolTip {
            get {
                return ResourceManager.GetString("KinahEarnedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinah.
        /// </summary>
        internal static string KinahMainViewMenuHeader {
            get {
                return ResourceManager.GetString("KinahMainViewMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent:.
        /// </summary>
        internal static string KinahSpentToolTip {
            get {
                return ResourceManager.GetString("KinahSpentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageMenuHeader {
            get {
                return ResourceManager.GetString("LanguageMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate Log....
        /// </summary>
        internal static string LocateLogMenuHeader {
            get {
                return ResourceManager.GetString("LocateLogMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Language.
        /// </summary>
        internal static string LogLanguageMenuHeader {
            get {
                return ResourceManager.GetString("LogLanguageMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main View.
        /// </summary>
        internal static string MainViewMenuHeader {
            get {
                return ResourceManager.GetString("MainViewMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        internal static string MinimizeBtnToolTip {
            get {
                return ResourceManager.GetString("MinimizeBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A player with this name already exists..
        /// </summary>
        internal static string NameTakenMessage {
            get {
                return ResourceManager.GetString("NameTakenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string OpacitySliderToolTip {
            get {
                return ResourceManager.GetString("OpacitySliderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate chat log. Please refer to the documentation for instructions on setting up Aion to create the log or click &quot;{0} -&gt; {1}&quot;.
        /// </summary>
        internal static string OpenLogError {
            get {
                return ResourceManager.GetString("OpenLogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string OptionsBtnToolTip {
            get {
                return ResourceManager.GetString("OptionsBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        internal static string PercentMainViewMenuHeader {
            get {
                return ResourceManager.GetString("PercentMainViewMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Off.
        /// </summary>
        internal static string PowerOffBtnTooltip {
            get {
                return ResourceManager.GetString("PowerOffBtnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power On.
        /// </summary>
        internal static string PowerOnBtnTooltip {
            get {
                return ResourceManager.GetString("PowerOnBtnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All.
        /// </summary>
        internal static string RemoveAllEncountersMenuHeader {
            get {
                return ResourceManager.GetString("RemoveAllEncountersMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string RemoveEncounterMenuHeader {
            get {
                return ResourceManager.GetString("RemoveEncounterMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All.
        /// </summary>
        internal static string ResetAllMenuHeader {
            get {
                return ResourceManager.GetString("ResetAllMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string ResetMenuHeader {
            get {
                return ResourceManager.GetString("ResetMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        internal static string ResizeThumbToolTip {
            get {
                return ResourceManager.GetString("ResizeThumbToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Alias....
        /// </summary>
        internal static string SetYouAliasMenuHeader {
            get {
                return ResourceManager.GetString("SetYouAliasMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string SortByDamageMenuHeader {
            get {
                return ResourceManager.GetString("SortByDamageMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS.
        /// </summary>
        internal static string SortByDpsMenuHeader {
            get {
                return ResourceManager.GetString("SortByDpsMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SortByNameMenuHeader {
            get {
                return ResourceManager.GetString("SortByNameMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        internal static string SortingMenuHeader {
            get {
                return ResourceManager.GetString("SortingMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Most.
        /// </summary>
        internal static string TopMostCheckBoxToolTip {
            get {
                return ResourceManager.GetString("TopMostCheckBoxToolTip", resourceCulture);
            }
        }
    }
}
